<?php include_once("header.php"); ?>
    <div class="container_1">
    	    <?php include_once("menu.inc.php"); ?>
            <div class="container_2">   
            	  <div id="about">
                  	<h2>Terms of Use</h2>
					<div class="separator"></div>
                    <article>
                    	<section>
							<p>This agreement is a legally binding contract between you (&ldquo;You&rdquo; or &ldquo;Your&rdquo;) and Dixie Auto Utah , its affiliates, subsidiaries and/or licensors (&ldquo;We,&rdquo; &ldquo;Us,&rdquo; or &ldquo;Our&rdquo;). This agreement governs Your use of Our websites operated by Us, including any site from which You access this agreement, which may include, but is not limited to, wattsautomotive.com (collectively, the &ldquo;Sites&rdquo;). We make the content on Our Sites, including all information, documents, communications, files, text, graphics, images, video, user interfaces, visual interfaces, photographs, software, metadata, audio/visual files, and other copyrightable material owned by or licensed to Us (collectively, the &ldquo;Materials&rdquo;), available for Your use subject to the Terms of Use set forth below. The Terms of Use spell out what you can expect from Us and what We expect from You.</p>
                            <h3 style="padding-top: 10px;">1. Acceptance of Terms of Use.</h3>
                            <p>You accept and agree to all terms, conditions and notices contained or referenced on the Sites (&ldquo;Terms of Use&rdquo;). Please read the following Terms of Use carefully. If you do not agree to the Terms of Use, do not use Our Sites. By accessing, shopping, using, or downloading in any way, without limitation, any Materials from Our Sites, or merely browsing Our Sites, You agree to and are bound by these Terms of Use.</p>
                            <p>We reserve the right to change the Terms of Use at any time. If we modify these Terms of Use, we will update the &ldquo;Date Last Modified&rdquo; and such changes will be effective upon posting. If we make material changes to the Terms of Use, we will notify you by prominently posting a notice on the Sites or by sending you a notice to the e-mail address we have on file for you. If You do not agree to the new Terms of Use, then You should stop using Our Materials and service.</p>
                            <h3 style="padding-top: 10px;">2. Intellectual Property Rights.</h3>
                              <div class="marginan-terms">
                              <h3 style="padding-top: 10px;">A. Copyright Information and Personal &amp; Non-Commercial Use Limitation.</h3>
                              <p>All Materials and the compilation of all content included on Our Sites are owned or licensed by Us and protected by United States and international copyright laws. We do not claim ownership of copyrights owned by third parties.</p>
                              <p>You have been granted a license to view and use the Materials subject to these Terms of Use. Unless otherwise specified, the Materials on Our Sites are for Your personal and non-commercial use. You may not sell or modify Materials or reproduce, display publicly or otherwise use the Materials in any way for any public or commercial purpose. Permission to reprint or electronically reproduce any document or graphic, in whole or in part, for any other purpose is expressly prohibited without prior written consent from Us. You may not provide copyrighted or other proprietary information to Us without permission from the owner of such material or rights. You are solely responsible for obtaining such permission and for any damages resulting from unauthorized disclosures or infringement.</p>
                              
                              <h3 style="padding-top: 10px;">B. Notice and Procedure for Making Claims under the Digital Millennium Copyright Act.</h3>
                              <p>The Digital Millennium Copyright Act (DMCA) provides recourse to copyright owners who believe that their rights under the United States Copyright Act have been infringed by acts of third parties over the Internet. If You believe that your copyrighted work has been copied without your authorization and is available on Our Sites in a way that may constitute copyright infringement, You may provide notice of Your claim to Our Designated Agent listed below. For your notice to be effective, it must include the following information:</p>
                              <ol>
                                  <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</li>
                                  <li>A description of the copyrighted work that you claim has been infringed upon;</li>
                                  <li>A description of where the material that you claim is infringing is located on this Sites;</li>
                                  <li>Information reasonably sufficient to permit the service provider to contact the complaining party, such as address, telephone number, and, if available, an e-mail address at which the complaining party may be contacted;</li>
                                  <li>A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and</li>
                                  <li>A statement that the information in the notification is accurate and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
                              </ol>
                              <div class="alignCenter">
                                  <u>Designated Agent:</u><br />
                                  Dixiemotors Utah<br />
                                  555 N. Bluff Street<br />
								  St. George, Utah                                
                              </div>
                              <p>The Designated Agent should be contacted only if You believe that Your work has been used or copied in a way that constitutes copyright infringement and such infringement is occurring on Our Sites. All other inquires to the Designated Agent will not be answered.</p>
                              
                              <h3 style="padding-top: 10px;">C. Trademarks.</h3>
                              <p>All other trademarks, product names, and company names and logos appearing on the Sites are the property of their respective owners.</p>
                              
                              <h3 style="padding-top: 10px;">D. Ideas and Inventions.</h3>
                              <p>All comments, feedback, suggestions, ideas, and other submissions (&ldquo;Ideas&rdquo;) disclosed, submitted, or offered to Us in connection with Your use of this Site shall become Our exclusive property. You agree that unless otherwise prohibited by law We may use, sell, exploit and disclose the Ideas in any manner, without restriction and without compensation to You.</p>
                         	 </div>
                            <h3 style="padding-top: 10px;">3. Privacy and Protection of Personal Information.</h3>
                            	<p>We respect the privacy of visitors to our Sites. Please see Our <a title="Privacy Policy" class="underlinan" href="privacy.php">Privacy Policy</a> relating to the collection and use of Your information. 
                                    You acknowledge and agree that this <a title="Privacy Policy" class="underlinan" href="privacy.php">Privacy Policy</a>, including, but not limited to, the manner in which We collect, use and disclose Your personally identifiable information, is incorporated and made part of these Terms of Use. 
                                    If You do not agree to each and every part of Our <a title="Privacy Policy" class="underlinan" href="privacy.php">Privacy Policy</a>, then You should not use the Sites or submit any personally identifiable information through Our Sites. 
                                    Questions regarding privacy issues should be directed to Us via e-mail at info@dixiemotorsutah.com<br />
                            	</p>
                            <h3 style="padding-top: 10px;">4. Disclaimer of Warranties and Limitation of Liability.</h3>
                            <p>	You expressly agree that use of Our Sites, services, and Materials is at Your sole risk. Neither We nor any of Our officers, directors, employees, agents, merchants, sponsors, licensors, component suppliers (both hardware and software), and/or any third party who provides products or services purchased from, used, transmitted or distributed by Us (collectively &ldquo;Providers&rdquo;), or the like, warrant that sites affiliated with Providers, including, but not limited to, Our Sites, will be uninterrupted, error-free, or free of viruses, worms, Trojan horses, keyboard loggers, spyware, adware, malware, harmful or malicious code, or other defects. The information, products and services published on Our Sites may contain inaccuracies or typographical errors. Furthermore, information You may provide to Us online may be lost or destroyed due to technical problems with Our systems that are beyond Our control. We make no warranty as to the results that may be obtained from the use of Our Sites or as to the accuracy, reliability, or currency of any information content, service, or merchandise provided through Our Sites.</p>
                   
                            <h3 style="padding-top: 10px;">5. Third Party Links.</h3>
                            <p>Our Sites may contain links to other websites and may forward users to other websites within the same Internet browser window. These websites are not under Our control, and the existence of a link on one of Our Sites does not imply any endorsement of the linked website(s) by Us or any affiliation between Us and the owners of the linked websites. We make no warranties or representations, and disclaim all liability, relating to the accuracy, content, terms of use, privacy policies, products, services, legality, reliability, viewpoint, accuracy, currency, decency, or any other aspect of the linked websites. You agree that We have no responsibility to You with respect to such material. We encourage you to examine the privacy policies and/or terms of use policies of any third party website.</p>
                            <h3 style="padding-top: 10px;">6. Online Conduct.</h3>
                            <p>You agree to use Our Sites and any services provided through Our Sites only for lawful purposes. Unacceptable uses of Our Sites include, without limitation: (i) engaging in any illegal activity or the planning of any illegal activity; (ii) disseminating or transmitting statements or material that, to a reasonable person, may be abusive, obscene, pornographic, defamatory, harassing, grossly offensive, vulgar, threatening or malicious; (iii) creating, disseminating or transmitting files, graphics, software or other material that actually or potentially infringe the copyright, trademark, patent, trade secret, publicity or other intellectual property rights of any person; (iv) creating a false identity or otherwise attempting to mislead any person as to the identity or origin of any communication; (v) exporting, re-exporting or permitting the downloading of any message, software or content in violation of any export or import law, regulation or restriction of the United States and its agencies or authorities, or without all required approvals, licenses or exemptions; (vi) interfering, disrupting or attempting to gain unauthorized access to other accounts on the Sites or any other computer network; (vii) disseminating or transmitting viruses, worms, Trojan horses, RATs, keyboard loggers, time bombs, spyware, adware, cancelbots or any other malicious or invasive code or program; or (viii) stalking or harassing another; (ix) disobeying any requirements, procedures, policies or regulations of networks connected to Our Sites; (x) engaging in any other activity deemed by Us to be in conflict with the spirit or intent of Our Sites.</p>
                            <h3 style="padding-top: 10px;">7. Circumvention.</h3>
                            <p>You acknowledge and agree that You shall not circumvent or attempt to circumvent any of these Terms of Use or the Materials offered through Our Sites or otherwise interrupt or attempt to interrupt the operations of the Sites (collectively, a &ldquo;Circumvention Act&rdquo;). If We determine, in Our sole discretion, that You have engaged, or attempted to engage, in any Circumvention Act, or to otherwise commit fraud with regard to the Sites, then, in such an event, We reserve the right to institute civil or criminal proceedings against You and to report You to the relevant regulatory authorities.</p>
                            <h3 style="padding-top: 10px;">8. Termination.</h3>
                            <p>These Terms of Use are effective until terminated by either party. You may terminate these terms at any time by discontinuing use of Our Sites. Your access to the Sites may be terminated immediately without notice from Us if in Our sole discretion You fail to comply with any term or provision of these Terms of Use.</p>
                            <h3 style="padding-top: 10px;">9. Security.</h3>
                            <p>We, and Our Providers, reserve the right to monitor all network traffic to Our Sites to identify and/or block unauthorized attempts or intrusions to upload or change information or cause damage to Our Sites in any fashion. Anyone using Our Sites expressly consents to such monitoring.</p>
                            <p>We reserve the right to fully cooperate with any law enforcement authorities or court order requesting or directing Us to disclose the identity of anyone posting any information, or publishing or otherwise making available any materials that are believed to violate these Terms of Use.</p>
                            <h3 style="padding-top: 10px;">10. Indemnification.</h3>
                            <p>You agree to defend, indemnify and hold Us and Our affiliates, subsidiaries, agents, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors harmless from and against all liabilities, actions, claims and expenses, including legal fees arising out of or relating to: (a) your use of the Sites or the Materials, including any data or work transmitted or received by You or any service provider; (b) Your violation of these Terms of Use; or (c) Your violation of any rights of a third party or service provider.</p>
                            <h3 style="padding-top: 10px;">11. Arbitration.</h3>
                            <p>Any dispute relating in any way to Your visit to any of Our Sites shall be submitted to confidential arbitration in American Fork, UT except that, to the extent You have in any manner violated or threatened to violate Our intellectual property rights, We may seek injunctive, equitable, or other appropriate relief in any state or federal court and You consent to exclusive jurisdiction and venue in the state and federal courts in the State of Utah. We agree that any Dispute between us shall be resolved exclusively and finally by arbitration administered by the American Arbitration Association (&ldquo;AAA&rdquo;), using interpretations under Utah law, and conducted under its Commercial Arbitration Rules and in accordance with its expedited hearing procedures, except as otherwise provided below. We will agree on another arbitration forum if AAA ceases operations. The arbitration will be conducted before a single arbitrator in American Fork, UT and will be limited solely to the Dispute between us. The arbitrator’s award, including attorneys’ fees, shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under these Terms of Use or Privacy Policy shall be joined to an arbitration involving any other party subject to these Terms of Use or Privacy Policy, whether through class arbitration proceedings or otherwise. You understand that, in the absence of this provision, You would have had a right to litigate disputes through a court, including the right to litigate claims on a class-wide or class action basis, and that you have expressly and knowingly waived those rights and agreed to resolve any Disputes through binding arbitration in accordance with the provisions of this paragraph. This arbitration provision shall be governed by the Federal Arbitration Act, 9 U.S.C. § 1, et seq. For the purposes of this provision, the term &ldquo;Dispute&rdquo; means any dispute, controversy, or claim arising out of or relating to: (i) these Terms of Use and/or Our Privacy Policy, its interpretation, or the breach, termination, applicability or validity thereof; (ii) the related order for, purchase, delivery, receipt or use of any product or service from Us; or iii) any other dispute arising out of or relating to the relationship between You and Us by way of Our Providers. Information may be obtained from the AAA online at www.adr.org, by calling 1-800-778-7879, or writing to 1633 Broadway, 10th Floor, New York, New York 10019.</p>
                            <h3 style="padding-top: 10px;">12. Applicable Law/Jurisdiction.</h3>
                            <p>By visiting Our Sites, even if accessed from a location outside the United States, you agree that the laws of the State of Utah will govern these disclaimers, Terms of Use and Privacy Policy, without giving effect to any principles of conflicts of laws. We reserve the right to make changes to Our Sites and these disclaimers, Terms of Use or Privacy Policy at any time. You hereby irrevocably and unconditionally consent to jurisdiction in the State of Utah.</p>
                            <h3 style="padding-top: 10px;">13. Waiver/Severability.</h3>
                            <p>Any failure by Us to require or enforce strict performance by You of any provision of these Terms of Use or to exercise any right under them shall not be construed as a waiver or relinquishment of Your right to assert or rely upon any such provision or right in that or any other instance.</p>
                            <p>The provisions of these Terms of Use are intended to be severable. If for any reason any provision of these Terms of Use shall be held invalid or unenforceable in whole or in part by any court of competent jurisdiction, such provision shall, as to such jurisdiction, be ineffective to the extent of such determination of invalidity or unenforceability without affecting the validity or enforceability thereof in any other manner or jurisdiction and without affecting the remaining provisions of the Terms of Use, which shall continue to be in full force and effect.</p>
                            <h3 style="padding-top: 10px;">14. Statute of Limitations.</h3>
                            <p>You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of Our Sites, Terms of Use and/or Privacy Policy must be filed within ONE (1) YEAR after such claim or cause of action arose or be forever barred.</p>
                            <h3 style="padding-top: 10px;">15. Entire Agreement.</h3>
                            <p>These Terms of Use constitute the entire agreement between us with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. Any waiver of any provision of the Terms of Use and/or Privacy Policy will be effective only if in writing and signed by Us.</p>
                        </section>        
                    </article>
                    
                  </div>  
<?php include_once("footer-information.php"); ?> 					
<?php include_once("footer.php"); ?> 